version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: my-great-repository-image  # Cambia el nombre de la imagen
    container_name: my-great-repository-docker-container  # Asegúrate de que sea único
    ports:
      - "3000:3000"  # Mapeo del puerto externo 3041 al interno 3000

volumes:
  node_modules:
